"""The scan's parameter frontier: bounded maps and the taps they imply."""

from slinoss.ops.scanprep.backends import (
    Backend,
    ScanPrepBackend,
    ScanPrepBackward,
    ScanPrepForward,
    get,
    names,
    register,
    resolve,
)
from slinoss.ops.scanprep.interface import ScanPrepFunction, scanprep
from slinoss.ops.scanprep.reference import (
    DRIVE_CEIL_SQ,
    DRIVE_FLOOR_SQ,
    LS_COLUMN,
    LS_MAX_MAG,
    PARAM_COLS,
    ROTVEC_COLUMNS,
    ScanGrads,
    ScanParams,
    anchored_rotvec,
    bounded_logscale,
    bounded_rotvec,
    check_dparams_out,
    foh_taps,
    pack_params,
    scanprep_bwd_ref,
    scanprep_ref,
)

__all__ = [
    "DRIVE_CEIL_SQ",
    "DRIVE_FLOOR_SQ",
    "LS_COLUMN",
    "LS_MAX_MAG",
    "PARAM_COLS",
    "ROTVEC_COLUMNS",
    "Backend",
    "ScanGrads",
    "ScanParams",
    "ScanPrepBackend",
    "ScanPrepBackward",
    "ScanPrepForward",
    "ScanPrepFunction",
    "anchored_rotvec",
    "bounded_logscale",
    "bounded_rotvec",
    "check_dparams_out",
    "foh_taps",
    "get",
    "names",
    "pack_params",
    "register",
    "resolve",
    "scanprep",
    "scanprep_bwd_ref",
    "scanprep_ref",
]
