"""CuTe kernels for the block norm and activation, both directions.

Importing this package imports the CuTe DSL. The reference path is
:mod:`slinoss.ops.block.reference` and needs neither the DSL nor a GPU.
"""

from slinoss.ops.block.cute.act import (
    ACT_THREADS,
    VECTOR_BYTES,
    swiglu_backward,
    swiglu_bwd,
    swiglu_bwd_kernel,
    swiglu_forward,
    swiglu_fwd,
    swiglu_fwd_kernel,
)
from slinoss.ops.block.cute.norm import (
    BWD_SLOTS,
    FWD_SLOTS,
    NORM_THREADS,
    SLOT_DOT,
    SLOT_SUMSQ,
    WARPS,
    norm_smem_bytes,
    reduce_tile,
    rmsnorm_backward,
    rmsnorm_bwd,
    rmsnorm_bwd_kernel,
    rmsnorm_forward,
    rmsnorm_fwd,
    rmsnorm_fwd_kernel,
    rmsnorm_residual_backward,
    rmsnorm_residual_bwd,
    rmsnorm_residual_bwd_kernel,
    rmsnorm_residual_forward,
    rmsnorm_residual_fwd,
    rmsnorm_residual_fwd_kernel,
    row_blocks,
    sm_count,
    total_tile,
)

__all__ = [
    "ACT_THREADS",
    "BWD_SLOTS",
    "FWD_SLOTS",
    "NORM_THREADS",
    "SLOT_DOT",
    "SLOT_SUMSQ",
    "VECTOR_BYTES",
    "WARPS",
    "norm_smem_bytes",
    "reduce_tile",
    "rmsnorm_backward",
    "rmsnorm_bwd",
    "rmsnorm_bwd_kernel",
    "rmsnorm_forward",
    "rmsnorm_fwd",
    "rmsnorm_fwd_kernel",
    "rmsnorm_residual_backward",
    "rmsnorm_residual_bwd",
    "rmsnorm_residual_bwd_kernel",
    "rmsnorm_residual_forward",
    "rmsnorm_residual_fwd",
    "rmsnorm_residual_fwd_kernel",
    "row_blocks",
    "sm_count",
    "swiglu_backward",
    "swiglu_bwd",
    "swiglu_bwd_kernel",
    "swiglu_forward",
    "swiglu_fwd",
    "swiglu_fwd_kernel",
    "total_tile",
]
